### PR TITLE
Add gitlab workflow and gitlens to vscode extensions

### PR DESCRIPTION
**Pull request by Ale-Cas**
Add [Gitlab](https://marketplace.visualstudio.com/items?itemName=GitLab.gitlab-workflow#ci-variable-autocompletion) and
[Gitlens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) to the vscode extensions installed in the devcontainer.

### CODE REVIEW

**Comment by lsorber** [comment]
Hi Alessio, thank you for the contribution! This project gives the user the choice between GitHub Actions and GitLab CI/CI, so I would like to make this extension conditional on the latter option. Would you like me to make that change, or do you prefer to do it?

**Comment by Ale-Cas** [comment]
HI 👍 No problem, I can do it. You mean only for the gitlab workflow extension right?

**Comment by lsorber** [comment]
Yes indeed, but also I'd rather not add the GitLens extension in this template (which we're trying to keep as minimal as we can).

**Comment by lsorber** [comment]
Closing because this PR will be superseded by https://github.com/radix-ai/poetry-cookiecutter/pull/223.

**Pull request closed without merging**
